networks:
  local:
    driver: bridge

services:
  postgres:
    container_name: postgres
    build: 
      context: ./db
      dockerfile: dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
       - ./postgres:/data/postgres/
    networks: 
       - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  golang:
    container_name: go
    build: 
      context: ./
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      
    networks: 
      - local


