networks:
  local:
    driver: bridge
services:
  postgres:
    container_name: postgres
    build: 
      context: ./db
      dockerfile: dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
       - ./postgres:/data/postgres/
    networks: 
       - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  golang:
    container_name: go
    build: 
      context: ./
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks: 
      - local

volumes:
  postgres:
    driver: local
