CREATE TABLE songs (
    songId          INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    groupName       TEXT,
    songName        TEXT,
    releaseDate     TEXT,
    songText        TEXT,
    songLink        TEXT
);

INSERT INTO songs (groupName, songName, releaseDate, songText, songLink) VALUES ('Marcus Tullius Cicero', 'De finibus bonorum et malorum', '45 BCE', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ut dui velit. Nulla facilisi. Pellentesque elementum egestas maximus. Mauris elementum nec neque vitae faucibus.\nSed commodo nunc quis elit rutrum blandit. Sed tristique, sapien vel consectetur ultrices, elit felis luctus nunc, sed ornare diam tortor eget leo. Nunc quis dapibus orci, sit amet dictum nibh. Duis a sollicitudin nisi.\n\nVestibulum pulvinar sodales luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus dictum ipsum justo, et luctus neque vehicula et.\nIn egestas interdum gravida. Sed vehicula ultricies enim sed pellentesque. Sed quis lacinia ligula. Praesent eget ante luctus, molestie orci non, accumsan ligula.\n\nMauris at nulla nisi. Proin porta libero ut condimentum viverra. Integer diam dolor, dictum non mi non, vehicula sollicitudin arcu. Aenean vitae urna quis metus pharetra venenatis sed eget nunc.\nNam a erat in dui tincidunt posuere. Integer vehicula vestibulum blandit. Nam dignissim ultricies augue a viverra. Donec tincidunt mattis dolor, et tempus lectus ornare nec. Aliquam posuere pretium libero.', 'https://en.wikipedia.org/wiki/De_finibus_bonorum_et_malorum');
INSERT INTO songs (groupName, songName, releaseDate, songText, songLink) VALUES ('Ken Blast', 'The Top', '2011-08-11', 'Final lap; I''m on top of the world\nAnd I will never rest for second again\nOne more time I have beaten them out\nThe scent of gasoline announces the end\nThey all said I''d best give it up\nWhat a fool, to believe their lie-ie-ies!\nNow they''ve fallen, I''m at the top\nAre you ready now to die-ie-ie?\nI came up from the bottom\nAnd into the top\nFor the first time I feel alive\nI can fly like an eagle\nAnd strike like a hawk\nDo you think you can survive... the top?\nOne more turn and I''ll settle the score\nA rubber fire screams into the night\nCrash and burn is what you''re gonna do\nI am the master of the asphalt fight\nThey all said I''d best give it up\nWhat a fool, to believe their lie-ie-ies!\nNow they''ve fallen, I''m at the top\nAre you ready now to die-ie-ie?\nI came up from the bottom\nAnd into the top\nFor the first time I feel alive!\nI can fly like an eagle\nAnd strike like a hawk\nDo you think you can survive...\nI came up from the bottom\nAnd into the top\nFor the first time I feel alive!\nI can fly like an eagle\nAnd strike like a hawk\nDo you think you can survive... the top?\nWhat were you thinking, telling me to change my game?\nThis style wasn''t going anywhere; it was kaput!\nYou want to see what I''\ve done with this place; this whole thing?\nYou want to see that I changed the game?\nNo, I AM the game!\nBefore I knew where this was going, I would''ve listened to you\nRight now, I distance myself from what you have to say!\nI made this something way bigger than you''re ever gonna be\nI made it this far; and I''m taking it to the top\nI came up from the bottom\nAnd into the top\nFor the first time I feel alive!\nI can fly like an eagle\nAnd strike like a hawk\nDo you think you can survive...\nI came up from the bottom\nAnd into the top\nFor the first time I feel alive!\nI can fly like an eagle\nAnd strike like a hawk\nDo you think you can survive... the top?', 'https://www.youtube.com/watch?v=dmGf01wA7d8');
INSERT INTO songs (groupName, songName, releaseDate, songText, songLink) VALUES ('Frank Sinatra', 'Blue Moon', '1961-01-01', 'Blue moon, you saw me standing alone\nWithout a dream in my heart\nWithout a love of my own\nBlue moon, you knew just what I was there for\nYou heard me saying a prayer for\nSomeone I really could care for\nAnd then there suddenly appeared before me\nThe only one my arms will hold\nI heard somebody whisper, "Please adore me"\nAnd when I looked, the moon had turned to gold\nBlue moon\nNow I''m no longer alone\nWithout a dream in my heart\nWithout a love of my own\nAnd then there suddenly appeared before me\nThe only one my arms will ever hold\nI heard somebody whisper, "Please adore me"\nAnd when I looked, the moon had turned to gold\nBlue moon\nNow I''m no longer alone\nWithout a dream in my heart\nWithout a love of my own\nBlue moon\nNow I''m no longer alone\nWithout a dream in my heart\nWithout a love of my own', 'https://www.youtube.com/watch?v=Dw1ZC6sZjIY');
INSERT INTO songs (groupName, songName, releaseDate, songText, songLink) VALUES ('Derek Warfield', 'Get Out Ye Black & Tans', '2010-01-01', 'I was born on a Dublin street where the loyal drums did beat\nThe loving English feet, they walked all over us\nAnd every single night, when me dad would come home tight\nHe''d invite the neighbors out with this chorus\nCome out ye Black and Tans\nCome out and fight me like a man\nShow your wife how you won medals down in Flanders\nTell her how the I-R-A made you run like hell away\nFrom the green and lovely lanes of Killashandra\nCome, let us hear you tell how you slandered great Parnell\nWhen you thought him well and truly persecuted\nWhere are the sneers and jeers that you loudly let us hear\nWhen our leaders of ''16 were executed?\nCome out ye Black and Tans\nCome out and fight me like a man\nShow your wife how you won medals down in Flanders\nTell her how the I-R-A made you run like hell away\nFrom the green and lovely lanes of Killashandra', 'https://www.youtube.com/watch?v=nmxueMo9qMU');
