basePath: /api/
definitions:
  musiclib.Song:
    properties:
      group:
        type: string
      id:
        type: string
      link:
        type: string
      name:
        type: string
      releaseDate:
        type: string
      text:
        type: string
    type: object
  musiclib.SongPaginated:
    properties:
      group:
        type: string
      id:
        type: string
      link:
        type: string
      name:
        type: string
      releaseDate:
        type: string
      text:
        items:
          type: string
        type: array
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a simple swagger for musiclib.
  title: MusicLib
  version: "0.1"
paths:
  /v1/songs:
    get:
      description: Gets song from db
      parameters:
      - description: id/group/name/date/text/link
        in: query
        name: sort
        type: string
      - description: int > 0
        in: query
        name: page
        type: integer
      - description: int > 0
        in: query
        name: items
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/musiclib.Song'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal error
      summary: Get song
      tags:
      - Songs
    post:
      consumes:
      - application/json
      description: Posts song to db
      parameters:
      - description: Song JSON Object
        in: body
        name: json
        required: true
        schema:
          example: '{"group":"sample", "name":"mamedsd", "releaseDate":"2030-12-12",
            "text":"ss", "link":"sss"}'
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal error
      summary: Post song
      tags:
      - Songs
  /v1/songs/{songId}:
    delete:
      description: deletes song from db
      parameters:
      - description: id
        in: path
        name: songId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "204":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal error
      summary: Delete song
      tags:
      - Songs
    get:
      description: Gets song from db
      parameters:
      - description: int >= 0
        in: query
        name: offset
        type: integer
      - description: int > 0
        in: query
        name: limit
        type: integer
      - description: id
        in: path
        name: songId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/musiclib.SongPaginated'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal error
      summary: Get song
      tags:
      - Songs
    patch:
      description: Patch song from db
      parameters:
      - description: Song JSON Object
        in: body
        name: json
        required: true
        schema:
          example: '{"group":"Patched", "name":"PatchedName", "releaseDate":"2023-12-12",
            "text":"PatchedText", "link":"PatchedLink"}'
          type: string
      - description: id
        in: path
        name: songId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal error
      summary: Patch song
      tags:
      - Songs
schemes:
- http
swagger: "2.0"
