basePath: /api/
definitions:
  musiclib.Song:
    properties:
      group:
        type: string
      id:
        type: string
      link:
        type: string
      name:
        type: string
      releaseDate:
        type: string
      text:
        type: string
    type: object
  musiclib.SongPaginated:
    properties:
      group:
        type: string
      id:
        type: string
      link:
        type: string
      name:
        type: string
      releaseDate:
        type: string
      text:
        items:
          type: string
        type: array
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a simple swagger for musiclib.
  title: MusicLib
  version: "0.1"
paths:
  /v1/songs:
    get:
      description: Gets list of songs from DB, with filters and pagination.
      parameters:
      - description: Filter by id, group, name, date, text or link.
        in: query
        name: filter
        type: string
      - description: Number of the page.
        in: query
        name: page
        type: integer
      - description: How many items to display per page.
        in: query
        name: items
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/musiclib.Song'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal error
      summary: Get songs
      tags:
      - Songs
    post:
      consumes:
      - application/json
      description: Post song to DB.
      parameters:
      - description: Song JSON Object
        in: body
        name: json
        required: true
        schema:
          example: '{"group":"Author name", "name":"Song name", "releaseDate":"2024-12-12",
            "text":"Lyrics", "link":"Link"}'
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal error
      summary: Post song
      tags:
      - Songs
  /v1/songs/{songId}:
    delete:
      description: Delete song from DB.
      parameters:
      - description: Id of a song to delete
        in: path
        name: songId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "204":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal error
      summary: Delete song
      tags:
      - Songs
    get:
      description: Get a song from DB, with pagination for verses.
      parameters:
      - description: Verse offset.
        in: query
        name: offset
        type: integer
      - description: How many verses to display.
        in: query
        name: limit
        type: integer
      - description: Id of the song.
        in: path
        name: songId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/musiclib.SongPaginated'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal error
      summary: Get song
      tags:
      - Songs
    patch:
      description: Update song specified by id.
      parameters:
      - description: Song JSON Object
        in: body
        name: json
        required: true
        schema:
          example: '{"group":"Patched", "name":"PatchedName", "releaseDate":"2023-12-12",
            "text":"PatchedText", "link":"PatchedLink"}'
          type: string
      - description: Id of a song to patch.
        in: path
        name: songId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal error
      summary: Patch song
      tags:
      - Songs
schemes:
- http
swagger: "2.0"
